### ISSUE TITLE
تبدیل تاریخ میلادی به شمسی 

### ISSUE THREAD

**Issue by d4rk-n0153** [ghodsizadeh/jalali-pandas#3]
برای تبدیل تاریخ میلادی به شمسی (جلالی) اگر تاریخ به صورت یک اعداد هشت رقمی در ستون اعداد وارد شده باشد کتابخانه با اررور مواجه می شود برای مثال
20211202
تبدیل به 
1400-09-11
یا
1400/09/11
یا
14000911
نمی شود

**Comment by ghodsizadeh** [comment]
سلام و درود.

بله این کار رو انجام نمیده شما اول باید این تاریخ رو به تایپ `datetime` پایتون تبدیل کنید مثلا با
`pd.to_datetime` 
و بعدش از این تبدیل رو انجام بدید.

تبدیل‌ها همه به تایپ  `datetime` هست و هیچکدوم `string` نیست.
من شخصا ندیدم که تایپ `int` رو هم به میلادی مستقیم تبدیل کنند اگر شما جایی دیدید بگید بررسی کنم.
